name: Infrastructure Management Router
run-name: ${{ github.event.inputs.action }} ${{ github.event.inputs.module }} in ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Action to perform'
        required: true
        options:
          - apply
          - destroy
      module:
        type: choice
        description: 'Module to manage'
        required: true
        options:
          - alb
          - eks
          - ec2
          - security_group
          - vpc
      environment:
        type: choice
        description: 'Environment to deploy to'
        required: true
        options:
          - dev
          - prod
          - preprod
        default: 'dev'
      resource_name:
        type: string
        description: 'Name of the resource'
        required: false
        default: ''
      run_post_deploy:
        type: choice
        description: 'Run post-deployment script (for EKS only)'
        required: true
        options:
          - 'false'
          - 'true'
        default: 'false'
      run_ingress_test:
        type: choice
        description: 'Run ingress testing script (for EKS only)'
        required: true
        options:
          - 'false'
          - 'true'
        default: 'false'

permissions:
  contents: read
  id-token: write

jobs:
  # Route to the appropriate workflow based on action
  route_to_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Route to apply workflow
        if: github.event.inputs.action == 'apply'
        uses: ./.github/workflows/apply.yml
        with:
          module: ${{ github.event.inputs.module }}
          environment: ${{ github.event.inputs.environment }}
          resource_name: ${{ github.event.inputs.resource_name }}
          run_post_deploy: ${{ github.event.inputs.run_post_deploy }}
          run_ingress_test: ${{ github.event.inputs.run_ingress_test }}
      
      - name: Route to destroy workflow
        if: github.event.inputs.action == 'destroy'
        uses: ./.github/workflows/destroy.yml
        with:
          module: ${{ github.event.inputs.module }}
          environment: ${{ github.event.inputs.environment }}
          resource_name: ${{ github.event.inputs.resource_name }}
